// <auto-generated />
namespace CalculadoraRecetas.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NuevosCamposCliente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NuevosCamposCliente));
        
        string IMigrationMetadata.Id
        {
            get { return "201901150021289_NuevosCamposCliente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
